point-of-sale-app/api-server/pom.xml, point-of-sale-app/inventory/pom.xml, point-of-sale-app/payments/pom.xml, point-of-sale-app/pom.xml, point-of-sale-app/service-sdk/pom.xml
- [Post from springboot](https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot)
- [CVE-2021-44228 Detail](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)
=> security: update log4j to 2.15

point-of-sale-app/pom.xml
- [Post from springboot](https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot)
- [CVE-2021-44228 Detail](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)
1. Deploy a GKE cluster
2. Ensure that `KUBECONFIG` points to this cluster in your local terminal
3. Update the `skaffold.yaml` file in the `<repo_root>/point-of-sale-app` path
**replace */rotation-week-dec3* with the name of your project**
4. Update the K8s yaml files inside `<repo_root>/point-of-sale-app/kubernetes-manifests` to point to the above image urls
5. Run `skaffold run --default-repo=gcr.io/<PROJECT_NAME>`
6. Create a proxy to the api-server `kubectl port-forward <api-server-pod-name> 8080:8080`
7. Visit: **localhost:8080** and validate if the app works
- #18
=> security: update log4j to 2.16

point-of-sale-app/pom.xml
As recently reported on [apache.org](https://logging.apache.org/log4j/2.x/security.html)
Apache Log4j2 versions 2.0-alpha1 through 2.16.0 did not protect from uncontrolled recursion from self-referential lookups. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data that contains a recursive lookup, resulting in a StackOverflowError that will terminate the process. This is also known as a DOS (Denial of Service) attack.
So, log4j should be updated from 2.16.0 to 2.17.0 to prevent this security risk.
=> security: update log4j to 2.17.0

point-of-sale-app/pom.xml
This PR bumps `log4j` to `2.17.1` to mitigate [CVE-2021-44832](https://logging.apache.org/log4j/2.x/).
=> Bump log4j to 2.17.1

renovate.json
- Renovate is trying to bump npm version: #52 
- This is conflict with the node version we use
- Add a package rule in the renovate settings to ensure npm stay at minor version`8.1.x`
=> fix: pin npm version from renovate bump

point-of-sale-app/ui/.eslintignore, point-of-sale-app/ui/.eslintrc.js, point-of-sale-app/ui/package-lock.json, point-of-sale-app/ui/package.json, point-of-sale-app/ui/src/App.vue, point-of-sale-app/ui/src/components/ItemList.vue, point-of-sale-app/ui/src/components/MainPage.vue, point-of-sale-app/ui/src/components/TransactionView.vue, point-of-sale-app/ui/src/main.js, point-of-sale-app/ui/src/mixins/titleMixin.js, point-of-sale-app/ui/src/services/RetailEdge.js, point-of-sale-app/ui/src/services/Util.js, point-of-sale-app/ui/vue.config.js
- We had `eslint` dependency on the ui service and a `lint` task under `scripts` of package.json
- However, the `lint` task uses the `vue-service linter` which was installed; thus this never worked
- We don't need both  `vue-service linter`and `eslinter` 
- So removed the eslinter and installed just `vue-service linter`
- Also ran the linter and fixed all raised issues
=> fix: remove eslint dependency and use vue-linter

anthos-baremetal-edge-deployment/README.md, anthos-baremetal-edge-deployment/inventory/group_vars/all.yaml
- We are renaming the repo to `point-of-sale` from `anthos-edge-usecases`
- So we need to have this PR ready for merge as soon as we do the renaming
- This will not be merged until we do the rename
=> chore: rename the repo name references

point-of-sale-app/README.md, point-of-sale-app/skaffold.yaml
The goal of this PR is to improve the usability of examples for Skaffold users. Removing the `us-docker.pkg.dev/anthos-dpe-abm-edge-pos/abm-edge-pos-images/` image prefix will allow to run examples with just the `--default-repo` option and without having to modify the `skaffold.yaml`.
Took example from this: https://github.com/GoogleContainerTools/skaffold/pull/3368
=> cleanup: Remove default image prefix in `skaffold.yaml`

renovate.json
- Stop renovate from bumping major versions of Vue. 
- Bumping Vue version needs bumping of other dependencies used which can be in conflict
- So we want to do it diligently only when needed.
- https://github.com/GoogleCloudPlatform/point-of-sale/pull/74
=> cleanup: renovate skip vue major version updates

point-of-sale-app/pom.xml
Based on [this doc from `Jib`](https://github.com/GoogleContainerTools/jib/blob/master/docs/default_base_image.md#migration-from-pre-30):
> However, even when you decide to keep using Distroless, at least we strongly recommend gcr.io/distroless/java-debian10:11, because, as of Apr 2021, gcr.io/distroless/java:{8,11} is based on Debian 9 that reached end-of-life. (Note gcr.io/distroless/java-debian10 doesn't have :8.)
And when looking at the [`distroless` repo](https://github.com/GoogleContainerTools/distroless/tree/main/java), there is even this [new update/recommendation since 2021-12](https://github.com/GoogleContainerTools/distroless/commit/d4ef1e32e0bdbf694f20b69f71766d72b1adc667#diff-0c997611c3c5fb9fa0641cb88e5aaa485b5fbc7293676fc28afab310dd430812) hence this update with …
=> cleanup: update distroless image 

point-of-sale-app/skaffold.yaml
- The extra lines at the end `skaffold.yaml` is breaking the skaffold run
=> fix: remove incorrect delimiter in skaffold

.github/cloudbuild/pos-pr-close.yaml, .github/cloudbuild/pos-pr-open-to-main.yaml, .github/cloudbuild/pos-pr-webhook-event.yaml
- In this PR a new [webhook event trigger](https://github.com/GoogleCloudPlatform/point-of-sale/settings/hooks) has been introduced in CloudBuild
- The webhook is specific to PullRequest event
- We add a cloudbuild config that checks if the event is of type `closed` (this included merge events as well) and if so then cleans up the PR specific resources in the test cluster
=> ci: add cloudbuild config for running on PR close event

point-of-sale-app/k8-manifests/README.md
ONly change was an extra space and indentations. No text was changed. You can see the [rendered view here](https://github.com/GoogleCloudPlatform/point-of-sale/blob/7fcf971d6695d54eea9db5e16bd41d30ff1d072f/point-of-sale-app/k8-manifests/README.md).
=> doc: add line breaks and indentation to make the README clear

renovate.json
Further fine tunes our renovate bot config setup
Applying some of the results of the survey. This is an example PR, but it adds stability days, concurrent PR limits, and adds config to bypass that if there is a security vulnerability.
* Sets prConcurrentLimit to 5, stabilityDays to 7
* Sets both prConcurrentLimit and stabilityDays to 0 if it is a CVE is reported
Note: we also have dependabot (which is built into Github) to notify us of security vulnerabilities. 
n/a
n/a
=> cleanup: added renovate bot config changes

.github/cloudbuild/pos-deploy-release.yaml, .github/cloudbuild/pos-pr-webhook-event.yaml, .github/cloudbuild/pos-push-to-main.yaml
- Post merge, the namespaces and resources created for PRs are not deleted
- This causes a resource limitation
- So we want to make sure when PRs are merged the namespaces created for them are removed
- Update the Cloudbuild trigger that runs on pushes to main to check and delete the most recently closed PR namespaces
=> imrpovement: cleanup namespaces

.github/cloudbuild/pos-push-to-main.yaml
- Make sure that we fetch the creds for dev cluster before deleting the namespaces
=> fix: ci to delete the stale namepaces

extras/anthos-vmruntime/README.md, extras/anthos-vmruntime/init-vm.sh
- Due to the environment variable in the `cat` command NOT being escaped, when the script file is created the script tries to substitute the environment variable. 
- However, since we want to just create a new file with that command in place, we don't want the shell to try to substitute this variable when `cat` is run
- So we escape it
=> bug: correct unescaped env variable error

.github/cloudbuild/pos-check-for-release.yaml, .github/cloudbuild/pos-pr-open-to-main.yaml, .github/cloudbuild/pos-publish-release-artifacts.yaml, .github/cloudbuild/pos-push-to-main.yaml
- The Github token used in the CI has expired
- So I am rotating it with a new token that is valid until end of this year
- It has been encrypted with the Key from the CLoud Key Management Service in the CI project and Base64 encoded
=> cleanup: rotate new token

.github/cloudbuild/pos-check-for-release.yaml, .github/cloudbuild/pos-pr-open-to-main.yaml, .github/cloudbuild/pos-publish-release-artifacts.yaml
- The last cloudbuild step in the CI failed for renovate PRs
- The step was using `gh` CLI to add comments to the PRs
- The reason for failure was because it was using the cloudbuilds **substitution variable**, **_HEAD_REPO_URL**. 
- This variable was pointing to the forked repo of renovate than this origin repo
- The forked repo does not have a PR openned - so it failed
- Update the cloudbuild files to use this repo as the source
=> bug: fix CI error for GitHub CLI

renovate.json
- Currently renovate runs everyday.
- This opens up updates to library versions that are very new with less 10% adoption
- So I have moved renovate updates to be quarterly (every 3 months)
=> chore: schedule renovate to run quarterly

.github/trusted-contribution.yml
This PR adds another entry for Renovate called `renovate-bot` in the trusted-contribution. This is to make sure to catch any instances of the Renovate bot opening PRs against this repository, which are currently not all caught (for example: https://github.com/GoogleCloudPlatform/point-of-sale/pull/224).
=> chore: Fix Renovate in trusted-contribution

.github/auto-approve.yml
This PR adds config for the auto-approve bot (documented here: https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-approve) which will approve Renovate PRs that follows very strict conventions and rules (e.g. only patches and minor bumps, all tests must be passing, etc.) Full details of these rules can be found in the previously linked README.
=> feat: Add auto-approve bot config

README.md, docs/domain-mapping.md, k8-manifests/util/certificates.yaml
Changes the `abm-pos.com` domain to `cymbal.dev`:
- `point-of-sale.retail.cymbal.dev`
- `im.point-of-sale.retail.cymbal.dev`
- `staging.point-of-sale.retail.cymbal.dev`
- `staging.im.point-of-sale.retail.cymbal.dev`
How to test? Verify that these links work as intended:
- https://point-of-sale.retail.cymbal.dev/
- https://staging.point-of-sale.retail.cymbal.dev/
=> chore: Change live demo domain to cymbal.dev

k8-manifests/release/inventory.yaml, k8-manifests/release/payments.yaml
The release manifest doesn't have the env var for MYSQL_HOST that was added to the dev profile in https://github.com/GoogleCloudPlatform/point-of-sale/pull/228
=> bug: update release manifest with MYSQL_HOST env
